import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import ThemeButton from "@/components/ThemeButton";

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  fallback: ['system-ui', 'sans-serif']
})

const lexend = Lexend({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
  fallback: ['system-ui', 'sans-serif']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lexend.variable} font-sans antialiased`}
      >
        <main>
          <ThemeButton />
          {children}
        </main>
      </body>
    </html>
  );
}
